### Project that we will compile:
CONTIKI_PROJECT = zol25

all: $(CONTIKI_PROJECT)
TARGET = zoul
CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
CONTIKI_TARGET_SOURCEFILES +=  dht22.c adc-sensors.c
